import { OnInit } from '@angular/core';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { AuthService } from '../../@core/service/auth.service';
import { AlertService } from '../../@core/service/alert.service';
import { Subscription } from 'rxjs';
import { MailTemplateService } from './services/mail-template.service';
import * as i0 from "@angular/core";
export declare class MailTemplateComponent implements OnInit {
    private _mailTemplateService;
    private _alertService;
    private _formBuilder;
    auth: AuthService;
    inputData: any;
    email: string;
    referralId: string;
    convertToZip: boolean;
    additionalDocuments: boolean;
    checked: boolean;
    email_template: string;
    packetId: string;
    document_packet_data: any;
    selectPacketName: string;
    emailTemplate: any;
    selectTemplate: string;
    isValidateRefferalid: boolean;
    referralAutoSuggestion: boolean;
    originalRefferalid: string;
    allEmailTemplateCategories: any;
    mailTempalateForm: UntypedFormGroup;
    referralAutoList: any;
    mailePacketInput: any;
    missingCategoryList: any;
    orgSubs: Subscription;
    orgId: any;
    pageList: any;
    constructor(_mailTemplateService: MailTemplateService, _alertService: AlertService, _formBuilder: UntypedFormBuilder, auth: AuthService);
    ngOnInit(): void;
    getAllPages(): void;
    changePage(_e: any): void;
    inititlize(): void;
    get mailTempalateFormControl(): {
        [key: string]: import("@angular/forms").AbstractControl<any, any>;
    };
    getPacketListing(): void;
    validatePacket(): void;
    confirmPacketMail(): void;
    validation(): any;
    checkCondition(data: any): any;
    selectMailId(data: any): void;
    openMailPacket(): void;
    closeMailPacket(): void;
    selectedTemp(data: any): void;
    getAllEmailTemplateCategories(): void;
    getEmailTemplateList(): void;
    getEmailTemplateNewList(): void;
    changeReferral(): void;
    onKeyUp($event: any): void;
    selectAddrss(data: any): void;
    getCategoryList(): any;
    getSubCategory(subcate: any): any;
    static ɵfac: i0.ɵɵFactoryDeclaration<MailTemplateComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MailTemplateComponent, "app-mail-template", never, { "inputData": { "alias": "inputData"; "required": false; }; }, {}, never, never, false, never>;
}
