export * from './lib/dynamic.service';
export * from './lib/dynamic.component';
export * from './lib/dynamic.module';
export { DynamicSearchModule } from './lib/pics-dynamic/dynamic-search/dynamic-search.module';
export { DynamicSearchComponent } from './lib/pics-dynamic/dynamic-search/dynamic-search.component';
export { DynmicTabPageModule } from './lib/pics-dynamic/dynamic-tab-page/dynmic-tab-page.module';
export { DynamicPageComponent } from './lib/pics-dynamic/dynamic-tab-page/dynamic-page/dynamic-page.component';
export { DynamicPageCleanupComponent } from './lib/pics-dynamic/dynamic-tab-page/dynamic-pagecleanup/dynamic-pagecleanup.component';
export { DynamicTabPageService } from './lib/pics-dynamic/@core/service/dynamic-tab-page-service';
export { DynamicsearchService } from './lib/pics-dynamic/@core/service/dynamicsearch.service';
