import { ElementRef, Injector, OnInit } from '@angular/core';
import { FormBuilder, UntypedFormGroup } from '@angular/forms';
import { AlertService } from '../../@core/service/alert.service';
import { YouthPhotoService } from '../@core/youth-photo.service';
import { HttpService } from '../../@core/service/http.service';
import { LocalService } from '../../@core/service/local.service';
import { ActivatedRoute, Router } from '@angular/router';
import { LocalStorageService } from '../../@core/local-storage/local-storage.service';
import { LoaderService } from '../../@core/service/loader.service';
import { AppService } from '../../@core/service/app.service';
import { PermissionStore } from '../../@core/store/permission.store';
import { SharedService } from '../../@core/service/shared.service';
import * as i0 from "@angular/core";
export declare class DocumentUploadComponent implements OnInit {
    private formBuilder;
    private route;
    private youthPhotoService;
    private httpService;
    private localStoreService;
    private storageService;
    private permissionStore;
    private appService;
    private sharedService;
    private localStorage;
    private router;
    documentUploadForm: UntypedFormGroup;
    alertService: AlertService;
    fileInput: ElementRef;
    imageHeight: number;
    imageWidth: number;
    isButtonShowHide: boolean;
    photoTypeList: any;
    fileName: any;
    fileSize: any;
    isImageUploaded: boolean;
    imgUrl: any;
    imgUrl2: any;
    photoId: any;
    youthPhotoDetails: any;
    settingInfo: any;
    showDescription: boolean;
    sourceKey: string;
    sourceValue: string;
    youthId: string;
    descriptionList: any[];
    defaultDescriptionList: any[];
    fileNamePath: string;
    workerId: any;
    loaderService: LoaderService;
    maxDate: any;
    previousType: any;
    isEditMode: boolean;
    fileSizeRaw: number;
    pageId: any;
    hidePrimaryFlag: boolean;
    hideReadAccess: boolean;
    pageAccess: any;
    assetAccess: any;
    enablePrimaryFlag: any;
    enableSaveButton: any;
    constructor(injector: Injector, formBuilder: FormBuilder, route: ActivatedRoute, youthPhotoService: YouthPhotoService, httpService: HttpService, localStoreService: LocalService, storageService: LocalStorageService, permissionStore: PermissionStore, appService: AppService, sharedService: SharedService, localStorage: LocalService, router: Router);
    ngOnInit(): void;
    initializeDocumentUploadForm(): void;
    uploadFile(fileValue: any): void;
    validateDocument(file: any): Promise<boolean>;
    sendDocument(): void;
    openModal(): void;
    resetValue(): void;
    clearImage(): void;
    getByPhotoId(): void;
    getDateFormat(value: any): any;
    resetData(): void;
    changeTypeValue(e: any): void;
    deletePhoto(): void;
    changeDescriptionValue(e: any): void;
    getPhysicalDescriptionList(): void;
    validateDescription(): void;
    getFileSize(fileSize: any): string;
    get moreDescription(): import("@angular/forms").AbstractControl<any, any>;
    static ɵfac: i0.ɵɵFactoryDeclaration<DocumentUploadComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DocumentUploadComponent, "app-document-upload", never, {}, {}, never, never, false, never>;
}
