import { CompactType, DisplayGrid, GridType } from "angular-gridster2";
export declare const options: {
    gridType: GridType;
    compactType: CompactType;
    margin: number;
    outerMargin: boolean;
    outerMarginTop: any;
    outerMarginRight: any;
    outerMarginBottom: any;
    outerMarginLeft: any;
    mobileBreakpoint: number;
    minCols: number;
    maxCols: number;
    minRows: number;
    maxRows: number;
    maxItemCols: number;
    minItemCols: number;
    maxItemRows: number;
    minItemRows: number;
    maxItemArea: number;
    minItemArea: number;
    defaultItemCols: number;
    defaultItemRows: number;
    fixedColWidth: number;
    fixedRowHeight: number;
    keepFixedHeightInMobile: boolean;
    keepFixedWidthInMobile: boolean;
    scrollSensitivity: number;
    scrollSpeed: number;
    enableEmptyCellClick: boolean;
    enableEmptyCellContextMenu: boolean;
    enableEmptyCellDrop: boolean;
    enableEmptyCellDrag: boolean;
    emptyCellDragMaxCols: number;
    emptyCellDragMaxRows: number;
    ignoreMarginInRow: boolean;
    draggable: {
        delayStart: number;
        enabled: boolean;
        ignoreContentClass: string;
        ignoreContent: boolean;
        dragHandleClass: string;
    };
    resizable: {
        delayStart: number;
        enabled: boolean;
        handles: {
            s: boolean;
            e: boolean;
            n: boolean;
            w: boolean;
            se: boolean;
            ne: boolean;
            sw: boolean;
            nw: boolean;
        };
    };
    swap: boolean;
    pushItems: boolean;
    disablePushOnDrag: boolean;
    disablePushOnResize: boolean;
    pushDirections: {
        north: boolean;
        east: boolean;
        south: boolean;
        west: boolean;
    };
    pushResizeItems: boolean;
    displayGrid: DisplayGrid;
    disableWindowResize: boolean;
    disableWarnings: boolean;
    scrollToNewItems: boolean;
};
